# Generated by Django 3.2.19 on 2024-06-29 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0003_department_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprroved_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_date', models.DateField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leaveid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leave')),
            ],
        ),
    ]
