# Generated by Django 3.2.19 on 2024-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20240629_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='staff_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
