# Generated by Django 3.2.19 on 2024-06-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_employee_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_balancer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.employee'),
        ),
    ]
