# Generated by Django 5.0.6 on 2024-06-30 18:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_remove_leave_user_leave_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aprroved_leave',
            new_name='Approved_leave',
        ),
    ]
