# Generated by Django 5.0.6 on 2024-07-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_rename_aprroved_leave_approved_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
