# Generated by Django 5.0.6 on 2024-07-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_leave_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
