# Generated by Django 5.0.6 on 2024-07-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_alter_leave_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='start_day',
            new_name='date_joined',
        ),
        migrations.AlterField(
            model_name='leave',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
