# Generated by Django 5.0.6 on 2024-07-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0016_rename_start_day_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetype',
            old_name='leave_type',
            new_name='type',
        ),
    ]
