# Generated by Django 5.0.6 on 2024-07-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0017_rename_leave_type_leavetype_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetype',
            old_name='type',
            new_name='name',
        ),
    ]
